spring.application.name=Agape

server.port=8082

# Dados da conexao enviada pelo Victor
spring.datasource.url=jdbc:postgresql://bdhomologacao.agapesistemas.com.br:59434/homologacao?sslmode=disable
spring.datasource.username=victor_gabriel
spring.datasource.password=agapeunit@26
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.ssl=false
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.max-lifetime=1800000