spring.application.name=Agape
server.port=8081

# Dados da conexão enviada pelo Victor
spring.datasource.url=jdbc:postgresql://bdhomologacao.agapesistemas.com.br:59434/homologacao
spring.datasource.username=victor_gabriel
spring.datasource.password=agapeunit@26
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true